[tool.poetry]
name = "hello-django"
version = "0.1.0"
description = ""
authors = ["Nikita Kuznetsov <nikita.kuznetsov512@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.1.7"

[tool.poetry.dev-dependencies]
gunicorn = "^20.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
